// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function sort(x) {
  return x.slice().sort();
}

function filterSort(x) {
  var x$1 = x.filter(function (x) {
        return x.includes(" ");
      });
  return x$1.slice().sort();
}

console.log(filterSort([
          "   ",
          "foo",
          " ",
          "bar",
          "     "
        ]));

console.log(filterSort([
          "     ",
          " ",
          "   "
        ]));

console.log(filterSort([
          "1",
          " 2",
          "3 ",
          " 4 ",
          "  5",
          "6  ",
          "  7  ",
          "8 8 8",
          " 9 9 "
        ]));

console.log(filterSort([
          " 1",
          "2 "
        ]));

console.log(filterSort([
          "a",
          " b",
          "c ",
          "d",
          "eeeee",
          "f  f",
          "gg",
          "  "
        ]));

exports.sort = sort;
exports.filterSort = filterSort;
/*  Not a pure module */
