// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");

function filterSort(arr, f) {
  return arr.slice().filter(Curry.__1(f)).sort();
}

function filterSpaceAndSort(arr) {
  return filterSort(arr, (function (x) {
                return x.includes(" ");
              }));
}

var partial_arg = [
  "   ",
  "foo",
  " ",
  "bar",
  "     "
];

console.log(function (param) {
      return filterSort(partial_arg, param);
    });

var partial_arg$1 = [
  "     ",
  " ",
  "   "
];

console.log(function (param) {
      return filterSort(partial_arg$1, param);
    });

var partial_arg$2 = [
  "1",
  " 2",
  "3 ",
  " 4 ",
  "  5",
  "6  ",
  "  7  ",
  "8 8 8",
  " 9 9 "
];

console.log(function (param) {
      return filterSort(partial_arg$2, param);
    });

var partial_arg$3 = [
  " 1",
  "2 "
];

console.log(function (param) {
      return filterSort(partial_arg$3, param);
    });

var partial_arg$4 = [
  "a",
  " b",
  "c ",
  "d",
  "eeeee",
  "f  f",
  "gg",
  "  "
];

console.log(function (param) {
      return filterSort(partial_arg$4, param);
    });

exports.filterSort = filterSort;
exports.filterSpaceAndSort = filterSpaceAndSort;
/*  Not a pure module */
