// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/rescript-jest/src/jest.bs.js");
var Main = require("../src/Main.bs.js");

Jest.describe("Main", (function (param) {
        var testExpect = function (toSort, expectedResult, msg) {
          Main.doThingsAndStuff(toSort);
          return Jest.test(msg, (function (param) {
                        return Jest.Expect.toEqual(Jest.Expect.expect(toSort), expectedResult);
                      }));
        };
        testExpect([
              "asdf",
              " ",
              "asdf2"
            ], [" "], "single space string");
        testExpect([
              "   ",
              "asdf",
              " ",
              "asdf2",
              "     "
            ], [
              "     ",
              " ",
              "   "
            ], "multiple spaces, order partially fixed");
        return testExpect([
                    "     ",
                    " ",
                    "   "
                  ], [
                    "     ",
                    "   ",
                    " "
                  ], "multiple spaces, order partially fixed");
      }));

/*  Not a pure module */
